# fly.toml app configuration file generated for blmc on 2024-04-16T14:51:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blmc'
primary_region = 'sjc'
kill_timeout = 60

[build]

[env]
  EULA = true
  MEMORY = "13G"
  AUTOSTOP_TIMEOUT_EST    = 120
  AUTOSTOP_TIMEOUT_INIT   = 120
  AUTOSTOP_PKILL_USE_SUDO = "TRUE"
  ENABLE_AUTO_STOP = "TRUE"
  # USES_PROXY_PROTOCOL = "true"
  VERSION = "1.19.2"
  TYPE = "AUTO_CURSEFORGE"
  CF_PAGE_URL = "https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6/files/4467529"
  MOTD = "And then the log lady said, let there be logs."
  CREATE_CONSOLE_IN_PIPE = "true"
  RESTIC_REPOSITORY = "/data/backups"
  RESTIC_PASSWORD = "i do not care"

[[services]]
  internal_port = 25565
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 0

  [[services.ports]]
    # handlers = ["proxy_proto"]
    port = 25565

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 2

[[mounts]]
  source = "data"
  destination = "data"
  processes = ["app"]

